#!/bin/bash

pkill reader
pkill writer
ipcrm -a

for((i = 0; i < $1; i++))
do
	bin/reader >$i		&
	bin/writer  /bin/bash		&
done

# waiting for all children processes
wait

for((i = 0; i < $1; i++))
do
	diff -up /bin/bash $i
#	rm $i
done

echo readers:
pgrep readers
echo writers:
pgrep writers
